In [ ]:
import numpy as np #kütüphaneyi dahil etme


In [ ]:
py=[np.arange(20)]#liste icinde 20 tane eleman olan bir dizi tanimladik
py

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19])]

In [ ]:
x=np.array(py)#bunu arraya dönüstürme

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [ ]:
x.shape

(1, 20)

In [ ]:
type(py)


list

In [ ]:
type(x)

numpy.ndarray

In [ ]:
r=np.arange(10,100,3)#10'dan 100 3'er 3'er dizi olusturma
r

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [ ]:
r=np.zeros(10)#sifirlardan olusan 10 elemanli bir dizi olusturma
r

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
r=np.ones(10)#birlerden olusan 10 elemanli bir dizi olusturma
r

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
r=np.linspace(0,100,5)#verilen araliklari belirtilen deger kadar esit parcaya böler
r

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
r=np.linspace(0,5,5)
r

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [ ]:
r=np.random.randint(1,1005)#1-1005 arasinda rastgele bir bir sayi üretme(random sayi)
r

29

In [ ]:
r=np.random.randint(0,10,101)#0-10 arasinda rastgele 101 tane sayi sec
r


array([0, 7, 2, 2, 8, 8, 4, 7, 6, 9, 3, 6, 9, 7, 0, 5, 8, 6, 6, 2, 7, 1,
       9, 0, 4, 9, 5, 5, 6, 1, 6, 0, 0, 5, 0, 3, 0, 4, 1, 4, 9, 9, 3, 9,
       2, 3, 7, 1, 7, 9, 8, 8, 4, 5, 0, 5, 2, 5, 0, 3, 4, 5, 6, 7, 1, 7,
       6, 1, 1, 6, 1, 9, 2, 1, 2, 9, 2, 7, 0, 4, 3, 0, 6, 3, 3, 0, 3, 0,
       1, 4, 1, 0, 7, 1, 1, 3, 3, 0, 0, 3, 0])

In [ ]:
r=np.random.rand(5)#0-1 arasinda 5 tane sayi üret
r

array([0.84538329, 0.61017197, 0.37086826, 0.28544134, 0.4616804 ])

In [ ]:
r=np.random.randn(5)#rastgele ondalikli  negatif sayilar da  üretir
r

array([ 1.02678767, -0.56953707, -0.63649804, -0.50310639, -0.61186121])

In [ ]:
r=np.arange(50)#0-50 arasinda bir dizi
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
r.reshape(5,10)#üstteki diziyi 5x10 seklinde tekrar sekillendirdik

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
np_array=np.arange(50)
np_multi=np_array.reshape(5,10)
np_multi.sum(axis=1)#satirlarin toplami

array([ 45, 145, 245, 345, 445])

In [ ]:
np_multi.sum(axis=0)#sütünlarin toplami

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [ ]:
a=np.random.randint(1,100,10)#10 tane random sayi üretme
a

array([27, 41, 18,  5, 65, 11, 64, 80, 11, 26])

In [ ]:
a.max()#dizinin maximum elemanini verir

80

In [ ]:
a.min()#dizinin minimum elemani

5

In [ ]:
a.mean()#dizinin ortalamasi

34.8

In [ ]:
a.argmax()#maximum sayinin indexini verir

7

###################################################################
Index Islemleri
###################################################################


In [ ]:
x=np.array(np.arange(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[5]#5inci indexi


5

In [ ]:
x[-1]#en sondaki index elamani

9

In [ ]:
x[0:3]#0 ile 3.indexe kadar olani yazdir

array([0, 1, 2])

In [ ]:
x[:3]#yukaridaki ile ayni anlamda en bastan basla manasi da var

array([0, 1, 2])

In [ ]:
x[3:]#3.indexten sona kadar olanlari al

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::]#bütün listeyi yaz

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::-1]#tersten yazmaya basla

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[::-2]#tersten 2ser 2ser atlayarak al

array([9, 7, 5, 3, 1])

In [ ]:
x2=np.array([np.arange(9)])
x2.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#cok boyutlu diziler

In [ ]:
n2=np.array([[1,2,3],[3,4,5],[6,7,8]])
n2

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
y=n2[1]
y

array([3, 4, 5])

In [ ]:
y=n2[2]
y

array([6, 7, 8])

In [ ]:
y=n2[0]
y

array([1, 2, 3])

In [ ]:
n2[1:2]#AxB

array([[3, 4, 5]])

In [ ]:
n2[0,2]

3

In [ ]:
n2[:,2]#her satirin 2.indexini al


array([3, 5, 8])

In [ ]:
n2

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
n2[:2,:2]#bastan ikinci indexe kadar satir ve sütünlari yaz

array([[1, 2],
       [3, 4]])

In [ ]:
n2[1:2,0:2]

array([[3, 4]])

In [ ]:
n2[:2,1:]

array([[2, 3],
       [4, 5]])

In [ ]:
n2[2,2]

8

#Numpy Operations

In [ ]:
num1=np.random.randint(10,100,6)
num2=np.random.randint(10,100,6)

In [ ]:
print("num1:",num1)
print("num2:",num2)

num1: [47 12 58 97 24 75]
num2: [11 71 60 18 73 85]


In [ ]:
top=num1+num2
top

array([ 58,  83, 118, 115,  97, 160])

In [ ]:
top=num1+10
top

array([ 57,  22,  68, 107,  34,  85])

In [ ]:
top=num1-num2
top

array([ 36, -59,  -2,  79, -49, -10])

In [ ]:
cikar=num1-10
cikar

array([37,  2, 48, 87, 14, 65])

In [ ]:
carp=num1*num2
carp

array([ 517,  852, 3480, 1746, 1752, 6375])

In [ ]:
tri=np.cos(num1)
tri

array([-0.99233547,  0.84385396,  0.11918014, -0.92514754,  0.42417901,
        0.92175127])

In [ ]:
log=np.log(num2)
log


array([2.39789527, 4.26267988, 4.09434456, 2.89037176, 4.29045944,
       4.44265126])

In [ ]:
resh=num1.reshape(2,3)
resh

array([[47, 12, 58],
       [97, 24, 75]])

In [ ]:
vertical=np.vstack((num1,num2))#vertical birlestirme
vertical

array([[47, 12, 58, 97, 24, 75],
       [11, 71, 60, 18, 73, 85]])

In [ ]:
horizontal=np.hstack((num1,num2))#horizontal birlestirme
horizontal

array([47, 12, 58, 97, 24, 75, 11, 71, 60, 18, 73, 85])

In [ ]:
re=num1>=5 #boolen deger sorgulama
re

array([ True,  True,  True,  True,  True,  True])

In [ ]:
print(num2)
re=num2<=30
re
#kontrol ettik bakalim gercekten dogur mu yapiyor diye :))

[11 71 60 18 73 85]


array([ True, False, False,  True, False, False])

In [ ]:
res=num2[re]#yukarida ki gecerli olan islemi yeni bir diziye atip yazdirdik
res

array([11, 18])

In [ ]:
#Numpy-Uygulama-
#burdan itibaren kendiniz ne islemler yapildiigni aciklamaya calisin :)  Ödev!

In [ ]:
re=np.array([10,15,30,45,60])
re

array([10, 15, 30, 45, 60])

In [ ]:
re=np.array(np.arange(5,15))
re

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
re=np.array(np.arange(50,100,5))
re

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [ ]:
zeros=np.zeros(10)
zeros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
ones=np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
esit_agirlikli=np.linspace(0,100,5)
esit_agirlikli

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
rastgele=np.random.randint(10,30,5)
rastgele

array([25, 19, 12, 26, 28])

In [ ]:
from numpy import random
random1=random.randn(10)
random1

array([ 0.48719719, -1.20510154, -0.41955982,  1.62981612, -1.28831575,
       -1.71872641, -0.18449234,  0.20768801, -1.31570759, -1.78671134])

In [ ]:
rastgele=np.random.randint(10,50,15)
rastgele

array([38, 46, 35, 30, 47, 49, 34, 36, 25, 20, 38, 23, 18, 33, 17])

In [ ]:
yeni_boyut=rastgele.reshape(3,5)
yeni_boyut

array([[38, 46, 35, 30, 47],
       [49, 34, 36, 25, 20],
       [38, 23, 18, 33, 17]])

In [ ]:
satir_top=yeni_boyut.sum(axis=1)
satir_top

array([196, 164, 129])

In [ ]:
sutun_top=yeni_boyut.sum(axis=0)
sutun_top

array([125, 103,  89,  88,  84])

In [ ]:
yeni_boyut.max()

49

In [ ]:
yeni_boyut.min()

17

In [ ]:
yeni_boyut.argmax()

5

In [ ]:
yeni_boyut.mean()

32.6

In [ ]:
a=np.random.randint(10,20,10)
a

array([10, 16, 15, 17, 19, 16, 12, 13, 16, 13])

In [ ]:
a[0:3]

array([10, 16, 15])

In [ ]:
a[::-1]

array([13, 16, 13, 12, 16, 19, 17, 15, 16, 10])

In [ ]:
yeni_boyut

array([[38, 46, 35, 30, 47],
       [49, 34, 36, 25, 20],
       [38, 23, 18, 33, 17]])

In [ ]:
yeni_boyut[2,3]

33

In [ ]:
yeni_boyut[:,0]

array([38, 49, 38])