In [ ]:
import numpy as np

In [ ]:
a=[1,2,3]
b=[1,5,10]
a=np.array(a)
b=np.array(b)

In [ ]:
a,b

(array([1, 2, 3]), array([ 1,  5, 10]))

In [ ]:
c=np.array([a,b])
c

array([[ 1,  2,  3],
       [ 1,  5, 10]])

In [ ]:
a.ndim,b.ndim,c.ndim

(1, 1, 2)

In [ ]:
c.shape

---


In [ ]:
c.dtype

dtype('int64')

In [ ]:
#bir dizinin belirlei bir hücersine erismek icin satir ve sütun numaralarini kullaniriz
c[0,1]#0'inci index 1-sutündaki eleman

2

In [ ]:
c

array([[ 1,  2,  3],
       [ 1,  5, 10]])

In [ ]:
c[0]#birinci satiri(0.index satirini verir)

array([1, 2, 3])

In [ ]:
c[0,1:]#0inci satirin 1,´.idexinden itibaren yazdir

array([[ 2,  3],
       [ 5, 10]])

In [ ]:
dizi_sifirlar=np.zeros((3,3))

In [ ]:
dizi_sifirlar

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#tüm degerleri ayni olan dizi
dizi1=np.full((4,4),50)#4x4lük bütün elemanlari 50 olan bir dizi yazdir
dizi1

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [ ]:
#random dizi olusturma
dizi2=np.random.rand(4,5)#0-1 arasinda degerler olusturur
dizi2

array([[0.54129153, 0.01085814, 0.33955916, 0.54696788, 0.03109519],
       [0.34620686, 0.17217625, 0.3813234 , 0.79405894, 0.92069385],
       [0.72474274, 0.56919936, 0.49699548, 0.36694202, 0.14447924],
       [0.26234419, 0.22975083, 0.52231429, 0.5221602 , 0.23701149]])

In [ ]:
#otomatik random int dizi olusturma
dizi3=np.random.randint(0,100,size=(5,5))#0-100 arasinda 5x5lik dizi olusturduk
dizi3

array([[12, 86, 55,  5, 22],
       [56,  4, 64, 37, 20],
       [ 3, 50, 84, 21, 38],
       [53, 96, 76, 33, 41],
       [97, 49, 92, 49,  4]])

In [ ]:
d=np.array([1,2,3,4])
print(d)

[1 2 3 4]


In [ ]:
d+4

array([5, 6, 7, 8])

In [ ]:
d*2

array([2, 4, 6, 8])

#Istatistik

In [ ]:
dizi4=np.array([[4,3,2,1],[5,6,7,8]])
dizi4

array([[4, 3, 2, 1],
       [5, 6, 7, 8]])

In [ ]:
np.min(dizi4)

1

In [ ]:
dizi4.sum()

36

In [ ]:
np.max(dizi4)

8

#Dosyadan dizi yükleme

In [ ]:
#masa üstünde kayitli olan ornek.txt deki virgülle ayrilmis elemanlari 
#buraya dizi seklinde aktardik-
filedata=np.genfromtxt('ornek.txt',delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[1 2 3 4 5 6 7]
 [8 9 7 8 9 9 8]
 [3 3 3 5 7 9 0]]


In [ ]:
filedata[0,1]

2